config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'lessons#index'
  get 'landing/index'
  resources :lessons do
    collection do
      post :save_editor_data
    end
  end
  resources :subjects
  resources :groups
  resources :users
end

app/models/group.rb
# frozen_string_literal: true

# Учебная группа, например ИВТ-5.5-07
class Group < ApplicationRecord
  validates :name, presence: true
  validates :academic_year, presence: true

  has_many :user_groups
  has_many :users, through: :user_groups
  has_many :group_subjects
  has_many :subjects, through: :group_subjects

  resourcify
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show

  end

  # GET /groups/new
  def new
    @group = Group.new
    @user = User.all.map { |u| [u.name, u.id] }
  end

  # GET /groups/1/edit
  def edit
    @user = User.all.map { |u| [u.name, u.id] }
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    respond_to do |format|
      if @group.save
        @group.user_ids = params[:user_groups_ids]
        @group.subject_ids = params[:group_subjects_ids]
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        @group.user_ids = params[:user_groups_ids]
        @group.subject_ids = params[:group_subjects_ids]
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :academic_year, :user_id, :subject_id)
  end

end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :academic_year %>
    <%= form.select :academic_year, (Time.zone.now.year - 4)..(Time.zone.now.year + 1) %>
  </div>

  <div class="field">
    <ul>
      <%= hidden_field_tag "user_groups_ids[]", nil %>
      <% User.all.each do |user| %>
        <li style="list-style: none; font-size: 16px; padding: 10px 0;">
          <%= check_box_tag "user_groups_ids[]", user.id, @group.user_ids.include?(user.id), id: dom_id(user) %>
          <%= label_tag dom_id(user), user.name %>
          <%=user.last_name %>
        </li>
      <%end %>
    </ul>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <%#= simple_form_for(@group) do |f| %>
    <%#= f.association :users, as: :check_boxes %>
    <%# f.collection_check_boxes(:user_ids, User.all, :id, :name) %>
  <%#end %>

<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.academic_year %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
<h2>
  <%= @group.name %>
</h2>
<p>
  <strong>Год начала обучения:</strong>
  <%= @group.academic_year %>
</p>

<p>
  <strong>Члены группы:</strong>
</p>
<ul>
  <% @group.users.each do |user|  %>
    <li>
      <%= user.name%>
      <%= user.last_name%>
    </li>
  <% end %>
</ul>

<p><strong>Лекции:</strong></p>
<ul>
  <%@group.subjects.each do |subject| %>
    <li>
      <%= subject.title %>
    </li>
    <% subject.lessons.each do |lesson|%>
      <ul>
        <li>
          <%= lesson.title %>
        </li>
      </ul>
    <%end%>
  <% end %>
</ul>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>