config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'lessons#index'
  get 'landing/index'
  resources :lessons do
    collection do
      post :save_editor_data
    end
  end
  resources :subjects
  resources :groups
  resources :users
end

app/models/subject.rb
# frozen_string_literal: true

# Предмет (учебная дисциплина)
class Subject < ApplicationRecord
  has_many :group_subjects
  has_many :groups, through: :group_subjects
  has_many :lessons

  resourcify
end

app/controllers/subjects_controller.rb
# frozen_string_literal: true

class SubjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_subject, only: %i[show edit update destroy]

  def index
    @subjects = Subject.all
    @lessons = Lesson.all
  end


  def show
  end

  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        @subject.group_ids = params[:group_subjects_ids]
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else

        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        @subject.group_ids = params[:group_subjects_ids]
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  #
  # def checkbox_items_output(parent, chain_check_item, item_ids)
  #   hidden_field_tag "#{item_ids}", nil
  #   parent.all.each do |item|
  #     def checked_item (item)
  #       return item_ids.include?(item.id), id: dom_id(item)
  #     end
  #     check_box_tag "#{item_ids}", item.id, chain_check_item.checked_item
  #     label_tag dom_id(item), item.name
  #   end
  # end

  private

  def set_subject
    @subject = Subject.find(params[:id])
  end

  def subject_params
    params.require(:subject).permit(:title, :group_id, lesson_ids:[])
  end
end

app/helpers/subjects_helper.rb
# frozen_string_literal: true

module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= hidden_field_tag "group_subjects_ids[]", nil %>
    <h4>Группы</h4>
    <ul>
      <% Group.all.each do |group| %>
        <li style="list-style: none">
          <%= check_box_tag "group_subjects_ids[]", group.id, subject.group_ids.include?(group.id), id: dom_id(group) %>
          <%= label_tag dom_id(group), group.name %>
        </li>
      <%end %>
    </ul>

  </div>

  <div class="field">
    <h4>Лекции</h4>

<!--    <p>-->
      <%#= form_with model: @subject do |lesson| %>
        <%#= lesson.collection_option(:lesson_id, Lesson.all, :id, :title, { :multiple => true}) %>
      <%# end %>
<!--    </p>-->
    <ul>
    <% Lesson.all.each do |lesson| %>
      <li style="list-style: none">
        <%= check_box_tag "subject[lesson_ids][]", lesson.id, subject.lesson_ids.include?(lesson.id), id: dom_id(lesson) %>
        <%= label_tag dom_id(lesson), lesson.title %>
      </li>
    <%end %>

      <%#=collection_check_boxes(:subject, :lesson_ids, Lesson.all, :id, :title) %>
    </ul>
    <%#= checkbox_items_output Lesson, subject, lesson_ids%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<section class="O_SubjectCollection level-2-heading">
  <div class="M_SectionHeader level-text">
    <h1>Предметы</h1>
    <button class="A_ButtonIcon button-text">
      Создать
      <i class='bx bx-plus bx-sm' ></i>
    </button>

  </div>

  <% @subjects.each do |subject| %>
    <div class="M_CategorySubjectName">
      <div class="A_CategoryTitle level-3-heading">
        <div>
          <i class='bx bxs-book-bookmark bx-sm' ></i>
          <h3><%= subject.title %></h3>
        </div>

       <%= link_to edit_subject_path(subject) do %>
         <i class='bx bx-dots-horizontal-rounded bx-sm'></i>
       <%end %>
      </div>

    </div>
    <div class="M_CardCollection col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3">
      <%subject.lessons.each do |lesson| %>
        <div class="M_CardLecture">
          <ul>
            <li>
              <%= lesson.title %>
            </li>
          </ul>
        </div>
    </div>


    <%end %>
    <%= link_to 'Show', subject %>

    <%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %>
    <hr width="50%" align="left">
  <% end %>


  <br>

  <%= link_to 'New Subject', new_subject_path %>
</section>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<h2>
  <%= @subject.title %>
</h2>

<p><strong>Лекции</strong></p>
<ul>
  <% @subject.lessons.each do |lesson|%>
    <li>
      <%= lesson.title %>
    </li>
  <%end%>
</ul>

<p><strong>Группы</strong></p>
<ul>
  <% @subject.groups.each do |group|%>
    <li>
      <%= group.name %>
    </li>
  <%end%>
</ul>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>